01-ai/Yi-1.5-9B-Chat:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 12
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1
HuggingFaceH4/zephyr-7b-alpha:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 12
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1
meta-llama/Meta-Llama-3-8B-Instruct:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 15
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.05

google/gemma-2b:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.05

google/gemma-7b:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.05
