

HuggingFaceH4/zephyr-7b-beta:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 64
  num_train_epochs: 12
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05

meta-llama/Llama-2-7b-chat-hf:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 64
  num_train_epochs: 12
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05
