google/gemma-2-9b-it:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 8
  lora_dropout: 0.05
google/gemma-7b-it:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 8
  lora_dropout: 0.05
Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 8
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.05

Qwen/Qwen1.5-7B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 8
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.05

google/gemma-2b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 8
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.05

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 8
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.05
