01-ai/Yi-1.5-9B-Chat:
  per_device_train_batch_size: 400
  gradient_accumulation_steps: 1600
  num_train_epochs: 800
  lora_rank: 1600
  lora_alpha: 3200
  lora_dropout: 0.05
HuggingFaceH4/zephyr-7b-alpha:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05
meta-llama/Meta-Llama-3-8B-Instruct:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05

HuggingFaceH4/zephyr-7b-beta:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05

meta-llama/Llama-2-7b-chat-hf:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05
